# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0003_auto_20171214_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='participante',
        ),
        migrations.DeleteModel(
            name='Inscripcion',
        ),
    ]
