# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eventos', '0004_auto_20171214_0739'),
        ('Usuarios', '0002_auto_20171029_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_inscripcion', models.CharField(blank=True, max_length=30)),
                ('estado_preinscripcion', models.CharField(blank=True, max_length=30)),
                ('estado_pago', models.CharField(blank=True, max_length=30)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eventos.Evento')),
                ('participante', models.ManyToManyField(to='Usuarios.Usuario')),
            ],
        ),
    ]
