# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado_inscripcion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado_pago',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado_preinscripcion',
            field=models.IntegerField(),
        ),
    ]
