# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fechaNoticia', models.DateField()),
                ('contenido', models.TextField()),
                ('imagen', models.CharField(max_length=100)),
            ],
        ),
    ]
