# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fechaNoticia', models.DateField()),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.DeleteModel(
            name='Noticias',
        ),
    ]
